#!/usr/bin/env python

"""import-fccs2ef.py: reads files containing mappings from FCCS fuelbed ids
to cover type ids, from covert type ids to EF groupings, and from EF groupings
to EF sets, and then writes the mappings out in more consise manner to new
data files
"""

__author__      = "Joel Dubowy"

import logging
import sys
import traceback

from afscripting import (
    args as scripting_args,
    utils as scripting_utils
)

from eflookup.fccs2ef.importer import (
    Fccs2CoverTypeImporter, CoverType2EfGroupImporter, EfGroup2EfImporter
)

# Note: though some argue that all required parameters should be specified as
# positional arguments, I prefer using 'options' flags, even though this
# means that there are required 'options', which is oxymoronic.

REQUIRED_OPTIONS = [
    # Input files
    {
        'short': "-a",
        'long': "--fccs-2-cover-type-input",
        'help': "csv containing mappings of FCCS fuelbed id to cover type id",
        'metavar': "FILE"
    },
    {
        'short': "-b",
        'long': "--cover-type-2-ef-group-input",
        'help': "csv containing mappings of cover type id to emission factor group",
        'metavar': "FILE"
    },
    {
        'short': "-c",
        'long': "--ef-group-2-ef-input",
        'help': "csv containing mappings of emission factor group to emission factors set",
        'metavar': "FILE"
    },
    # output Files
    {
        'short': "-x",
        'long': "--fccs-2-cover-type-output",
        'help': "Name of new, pruned and encoded fccs-2-covert-type csv",
        'metavar': "FILE"
    },
    {
        'short': "-y",
        'long': "--cover-type-2-ef-group-output",
        'help': "Name of new, pruned and encoded cover-type-2-ef-group csv",
        'metavar': "FILE"
    },
    {
        'short': "-z",
        'long': "--ef-group-2-ef-output",
        'help': "Name of new, pruned and encoded ef-group-2-ef csv",
        'metavar': "FILE"
    }
]
EXAMPLES_STRING = """
Example calls:
 $ ./dev/scripts/import-fccs2ct2ef \\
    -a ./input-data/orig-fccs2covertype.csv \\
    -b ./input-data/EFGroup_byCoverType.csv \\
    -c ./input-data/EFbyGroup_English.csv    \\
    -x ./eflookup/fccs2ef/data/fccs2covertype.csv \\
    -y ./eflookup/fccs2ef/data/covertype2efgroup.csv \\
    -z ./eflookup/fccs2ef/data/efgroup2ef.csv
 """

def main():
    parser, args = scripting_args.parse_args(REQUIRED_OPTIONS, [],
        epilog=EXAMPLES_STRING)

    try:
        fccs2ct_import = Fccs2CoverTypeImporter(args.fccs_2_cover_type_input)
        fccs2ct_import.write(args.fccs_2_cover_type_output)
        ct2efg_importer = CoverType2EfGroupImporter(args.cover_type_2_ef_group_input)
        ct2efg_importer.write(args.cover_type_2_ef_group_output)
        efg2ef_importer = EfGroup2EfImporter(args.ef_group_2_ef_input)
        efg2ef_importer.write(args.ef_group_2_ef_output)

    except Exception as e:
        scripting_utils.exit_with_msg(str(e) + '\n\n' + traceback.format_exc())

if __name__ == "__main__":
    main()
